name: OCIO
description: Osservatorio Civico indipendente sulla casa e sulla residenza
exclude: [README.md]
permalink: pretty
twitter: 
facebook: ocio.venezia
instagram: osservatorioociovenezia 
medium: ocio-venezia
github: veneziainrete
email: mail.veneziainrete@gmail.com
vimeo: 
url: http://ocio-venezia.it
logo: /img/logo.png

plugins:
  - jekyll-feed
