name: elaboratorio civico
description: elaboratorio civico
exclude: [README.md]
permalink: pretty
twitter: 
facebook: 
github: 
medium:
email: mail.veneziainrete@gmail.com
vimeo: 
url: 
logo: /img/logo.png

plugins:
  - jekyll-feed
