name: OCIO
description: Osservatorio Civico sulla casa e sulla residenzialità a Venezia
exclude: [README.md]
permalink: pretty
twitter: 
facebook: ocio.venezia
github: 
medium:
email: mail.veneziainrete@gmail.com
vimeo: 
url: 
logo: /img/logo.png

plugins:
  - jekyll-feed
